tales/users/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField
from wtforms import StringField, SubmitField, BooleanField, PasswordField
from wtforms.validators import DataRequired, EqualTo, length, ValidationError, Email
from tales.models import User
from flask_login import current_user

class RegistrationForm(FlaskForm):
    username = StringField('Username', validators = [DataRequired(), length(min =2, max =20)])
    email = StringField('Email', validators = [DataRequired(), Email()])
    password = PasswordField('Password', validators = [DataRequired()])
    confirm_password = PasswordField('Confirm password', validators = [DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign up')
    
    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('Username already taken.Please choose another')
        
    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('Email already taken.Please choose another')
    
class LoginForm(FlaskForm):
    email = StringField('Email', validators = [DataRequired(), Email()])
    password = PasswordField('Password', validators = [DataRequired()])
    submit = SubmitField('Sign in')
    remember = BooleanField('Remember me')
    
class UpdateForm(FlaskForm):
    username = StringField('Username', validators = [DataRequired(), length(min =2, max =20)])
    email = StringField('Email', validators = [DataRequired(), Email()])
    image = FileField('Upload Profile Picture', validators=[FileAllowed(['png', 'jpg'])])
    submit = SubmitField('Update')
    
    def validate_username(self, username):
        if username.data != current_user.username:
            user = User.query.filter_by(username=username.data).first()
            if user:
                raise ValidationError('Username already taken.Please choose another')
        
    def validate_email(self, email):
        if email.data != current_user.email:
            user = User.query.filter_by(email=email.data).first()
            if user:
                raise ValidationError('Email already taken.Please choose another')

class ResetRequest(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    submit = SubmitField('Request Password Reset')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user is None:
            raise ValidationError('That email has not been registered')

class ResetPassword(FlaskForm):
    password = PasswordField('Password', validators = [DataRequired()])
    confirm_password = PasswordField('Confirm password', validators = [DataRequired(), EqualTo('password')])
    submit = SubmitField('Reset Password')

tales/main/routes.py
from flask import render_template, request, Blueprint
from tales.models import Post

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home/')
def home():
    page = request.args.get('page', 1, type=int)
    post=Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', post=post)

@main.route('/about/')
def about():  
    return render_template('about.html', title='About')

tales/posts/routes.py
from flask import render_template, redirect, url_for, flash, request, abort, Blueprint
from flask_login import current_user, login_required
from tales.models import Post
from tales.posts.forms import UpdatePost
from tales import db

posts = Blueprint('posts', __name__)

@posts.route('/post/new/', methods=['GET', 'POST'])
@login_required
def new_post():
    form=UpdatePost()
    if form.validate_on_submit():
        flash('Your post has been created', 'success')
        post = Post(title=form.title.data, content=form.content.data, author=current_user )
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('main.home'))
    return render_template('addpost.html', title='Post', form=form, legend='New Post')

@posts.route('/post/<int:post_id>/')
def edit_post(post_id):
    post=Post.query.get_or_404(post_id)
    return render_template('editpost.html', post=post)

@posts.route('/post/<int:post_id>/update/', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post=Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    form = UpdatePost()     
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data      
        db.session.commit()
        flash('Post has been updated successfully', 'success')
        return redirect(url_for('posts.edit_post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('addpost.html', form=form, post=post, legend='Update Post')

@posts.route('/post/<int:post_id>/', methods=['POST'])
@login_required
def delete_post(post_id):
    post=Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Post has been deleted', 'success')
    return redirect(url_for('main.home'))

tales/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from tales import db, bcrypt
from tales.models import User, Post
from tales.users.forms import RegistrationForm, LoginForm, UpdateForm, ResetRequest, ResetPassword
from tales.users.utils import save_image, send_reset_email

users = Blueprint('users', __name__)

@users.route('/register/', methods = ['GET', 'POST'])
def registration():
    form = RegistrationForm()
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    if form.validate_on_submit():
        hashed_pwd = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_pwd)
        db.session.add(user)
        db.session.commit()
        flash('Account created successfully. You can now log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Registration', form=form)

@users.route('/login/', methods = ['GET', 'POST'])
def login():
    form = LoginForm()
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            wanted_page = request.args.get('next')
            login_user(user, remember=form.remember.data)
            return redirect(wanted_page) if wanted_page else redirect(url_for('main.home'))
        else:
            flash('Failed. Please check username and password', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route('/logout/')
def logout():
    logout_user()
    return redirect(url_for('users.login'))
    
@users.route('/account/', methods=['GET', 'POST'])
@login_required
def account():
    form=UpdateForm()
    if form.validate_on_submit():
        if form.image.data:
            pic_file=save_image(form.image.data)
            current_user.image=pic_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Account details have been updated successfully')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email 
    image_file= url_for('static', filename='profilepic/{}'.format(current_user.image))
    return render_template('account.html', title='Account', image_file=image_file, form=form)



@users.route('/user/<string:username>/')
def user_page(username):
    page = request.args.get('page', 1, type=int)
    user= User.query.filter_by(username=username).first_or_404()
    post = Post.query.filter_by(author=user).order_by(Post.date_posted.desc()).paginate(page=page, per_page=2)
    return render_template('user.html', user=user, post=post)

@users.route('/password_reset/', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = ResetRequest()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('Check your email for the link to reset your password')
        return redirect(url_for('users.login'))
    return render_template('request_token.html', title='Password Reset Request', form=form)

@users.route('/reset_password/<token>/', methods = ['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('The token is currently expired. Please make a new request.', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPassword()
    if form.validate_on_submit():
        hashed_pwd = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_pwd
        db.session.commit()
        flash('Your password has been updated. You can now log in.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

tales/templates/about.html
{% extends 'layout.html' %}
{% block content %}
    <div class="about-page">
        <div class="title">
            <h1>This is the About page</h1>
        </div>
    </div>
{% endblock %}

tales/templates/account.html
{% extends 'layout.html' %}
{% block content %}
<div class="account-page">
    <div class="title">
        <h1>This is your Account Page.</h1>
    </div>
    <div class="personal-info">
        <div class="image">
            <img src= '{{ image_file }}'>
        </div>
        <div class="user-title">
            <a href={{url_for('users.user_page', username=current_user.username)}}><h2>{{ current_user.username }}</h2></a>
            <h3>{{ current_user.email}}</h3>
        </div>
    </div>
    <div class="form-div account">
        <form method='POST' action='' enctype='multipart/form-data'>
            {{ form.hidden_tag() }}
            <fieldset>
                <legend>Update Account Details</legend>
                <div class="input-div">
                    {{ form.username.label (class_="form-label") }}
                        {% if form.username.errors %}
                            {{ form.username (class_="form-input")}}
                            <div class="error-div">
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{form.username (class_='form-input')}}
                        {% endif %}
                </div>
                <div class="input-div">
                    {{ form.email.label (class_="form-label") }}
                        {% if form.email.errors %}
                            {{ form.email }}
                            <div class="error-div">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{form.email(class_='form-input')}}
                        {% endif %}
                </div>
                <div class="input-div">
                    {{ form.image.label (class_="form-label") }}
                    {{ form.image (class_="submit-btn") }}
                    {% if form.image.errors %}
                        {% for error in form.image.errors %}
                            <br><span>{{ error }}</span>
                        {% endfor%}
                    {% endif %}
                </div>
            </fieldset>
            <div class="submit-div">
                {{ form.submit(class_="submit-btn")}}
            </div>
        </form>
    </div>
</div>
{% endblock %}

tales/templates/addpost.html
{% extends 'layout.html' %}
{% block content %}
    <div class='add-post'>
        <div class="title">
            <h1>Add a Blog Post here</h1>
        </div>
        <div class="form-div">
            <form method='POST' action = "">
                {{ form.hidden_tag() }}
                <fieldset>
                    <legend>{{legend}}</legend>
                    <div class="input-div">
                        {{ form.title.label (class_="form-label")}}
                        {% if form.title.errors %}
                            {{form.title (class_="form-input") }}
                            <div  class="error-div">
                                {% for error in form.title.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {%else %}
                            {{ form.title (class_="form-input")}}
                        {% endif %}
                    </div>
                    <div class="input-div">
                        {{ form.content.label (class_="form-label")}}
                        {% if form.content.errors %}
                            {{ form.content (class_='form-input content')}}
                            <div class="error-div">
                                {% for error in form.content.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {%else %}
                            {{ form.content (class_='form-input content')}}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="submit-div">
                    {{ form.submit (class_="submit-btn") }}
                </div>
            </form>
        </div>
    </div>
{% endblock  %}

tales/templates/editpost.html
{% extends 'layout.html' %}
{% block content %}
    <div class="edit-post">
        <div  class="title">
            <h1>This is the Edit Post page</h1>
        </div>
        <div class="post-container">
            {% if post.author == current_user %}
                <div class="edit-btns">
                    <a href={{url_for('posts.update_post', post_id=post.id)}}>Update</a>
                    <form action='{{url_for('posts.delete_post', post_id=post.id)}}' method='POST'>
                        <input type="submit" value="Delete">
                    </form>
                </div>
            {% endif %}
            <div class="article">
                <div class="post-image">
                    <img src='{{ url_for('static', filename='profilepic/{}'.format(post.author.image)) }}'>
                </div>
                <div class="post-author">
                    <a href={{url_for('users.user_page', username=post.author.username)}}>{{ post.author.username }}</a>
                    <small>{{ post.date_posted.strftime('%Y-%m-%d')}}</small>
                </div>
                <div class="post-content">
                    <a href={{url_for('posts.edit_post', post_id=post.id)}}>{{ post.title }}</a>
                    <p>{{ post.content}}</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

tales/templates/home.html
{% extends 'layout.html' %}
{% block content %}
    <div class="home-page">
        <div  class="title">
            <h1>This is the Home page</h1>
        </div>
        <div class="post-container">
            {% for post in post.items %}
                <div class="article">
                    <div class="post-image">
                        <img src='{{ url_for('static', filename='profilepic/{}'.format(post.author.image)) }}'>
                    </div>
                    <div class="post-author">
                        <h3><a href={{url_for('users.user_page', username=post.author.username)}}>{{ post.author.username }}</a></h3>
                        <small>{{ post.date_posted.strftime('%Y-%m-%d')}}</small>
                    </div>
                    <div class="post-content">
                        <h3><a href={{ url_for('posts.edit_post', post_id=post.id)}}>{{ post.title }}</a></h3>
                        <p>{{ post.content}}</p>
                    </div>
                </div>
            {% endfor %}
            <div class="pages">
                {% for page_num in post.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2)%}
                {% if page_num %}
                    {% if post.page == page_num %}
                        <a class="current-page" href={{url_for('main.home', page=page_num)}}>{{page_num}}</a>
                    {%else %}
                        <a class="other-pages" href={{url_for('main.home', page=page_num)}}>{{page_num}}</a>
                    {% endif %}
                {% else %}
                ...
                {% endif %}
            {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

tales/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <link rel='stylesheet' type='text/css' href={{url_for('static', filename='css/main.css')}}>
    <link rel="icon" href="/static/profilepic/title.jpg" type="image/jpg">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% if title %}
    <title>TheBlog - {{ title }}</title>
    {% else %}
    <title>TheBlog</title>
    {% endif %}
</head> 
<body>
    <header>
        <nav>
            <a href={{url_for('main.home')}}><img class="logo" src={{url_for('static', filename='profilepic/logo.jpg')}}></a>
            <a href = {{ url_for('main.home')}}>Home</a>
            <a href = {{ url_for('main.about')}}>About</a>
            {% if current_user.is_authenticated %}
                <a href={{ url_for('posts.new_post')}}>Post</a>                   
                <a href={{ url_for('users.account')}}>Account</a>                   
                <a href={{ url_for('users.logout')}}>LogOut</a>
            {% else %}
                <a href={{ url_for('users.login')}}>LogIn</a>
                <a href={{ url_for('users.registration')}}>Registration</a>
            {% endif %}
        </nav>
    </header>
    <main>
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    <div class="main-message">
                        {% for category, message in messages %}
                                <span>{{ message }}</span>
                        {% endfor %}
                    </div>
                {% endif %}
            {% endwith %}
        <div class="main-div">
            {% block content %} {% endblock %}
            <footer>
                <h5>Nelliville &copy 2024</h5>
            </footer>
        </div>
    </main>
</body>
</html>

tales/templates/login.html
{% extends 'layout.html' %}
{% block content %}
    <div class="form-page">
        <div class="title">
            <h1>Welcome back User</h1>
        </div>
        <div class="form-div">
            <form method='POST' action = "">
                {{ form.hidden_tag() }}
                <fieldset>
                    <legend>Login</legend>
                    <div class="input-div">  
                        {{ form.email.label (class_="form-label") }}
                            {% if form.email.errors %}
                                {{ form.email(class_="form-input") }}
                                <div class="error-div">
                                    {% for error in form.email.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else%}
                                {{ form.email(class_='form-input') }}
                            {% endif %}
                    </div>
                    <div class="input-div">
                        {{ form.password.label(class_="form-label") }}
                            {% if form.password.errors %}
                                {{ form.password(class_="form-input") }}
                                    {% for error in form.password.errors %}
                                    <div class="error-div">
                                        <span>{{ error }}</span>
                                    </div>
                                    {% endfor %}
                            {% else %}
                                {{ form.password(class_='form-input') }}
                            {% endif %}
                    </div>
                    <div class="input-div">
                        {{ form.remember.label(class_="remember") }}
                        {{ form.remember }}
                    </div>
                </fieldset>
                <div class="submit-div">
                    {{ form.submit(class_="submit-btn") }}               
                </div>
                <small>
                    <a href={{url_for('users.reset_request')}} >Forgot Password</a>
                </small>
                <div class="request">
                    <small>Need an account?Click <a href = {{ url_for('users.registration') }}>here</a></small>
                </div>   
            </form> 
        </div> 
    </div>   
{% endblock %}

tales/templates/register.html
{% extends 'layout.html' %}
{% block content %}
    <div class="form-page">
        <div class="title">
            <h1>This is the Registration page</h1>
        </div>
        <div class="form-div">
            <form method='POST' action = "">
                {{ form.hidden_tag() }}
                <fieldset>
                    <legend>Registration</legend>
                    <div class="input-div">  
                        {{ form.username.label (class_="form-label") }}
                            {% if form.username.errors %}
                                {{ form.username (class_="form-input") }}
                                <div  class="error-div">
                                    {% for error in form.username.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.username(class_='form-input')  }}
                            {% endif %}
                    </div>
                    <div class="input-div">  
                        {{ form.email.label(class_="form-label")}}
                            {% if form.email.errors %}
                                {{ form.email(class_="form-input") }}
                                <div class="error-div">
                                    {% for error in form.email.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.email(class_="form-input") }}
                            {% endif %}
                    </div>
                    <div class="input-div">
                        {{ form.password.label (class_="form-label")}}
                            {% if form.password.errors %}
                                {{ form.email(class_="form-input") }}
                                <div class="error-div">
                                    {% for error in form.password.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.password (class_="form-input")}}
                            {% endif %}
                    </div>
                    <div class="input-div">
                        {{ form.confirm_password.label (class_="form-label")}}
                        <div>
                            {% if form.confirm_password.errors %}
                                {{ form.confirm_password (class_="form-input")}}
                                <div class="error-div">
                                    {% for error in form.confirm_password.errors %}
                                        <span>{{ error }}</span>
                                    {% endfor %}
                                </div>
                            {% else %}
                                {{ form.confirm_password(class_="form-input") }}
                            {% endif %}
                        </div>
                    </div>
                </fieldset>
                    <div class="submit-div">
                        {{ form.submit(class_="submit-btn") }}
                    </div>
                <div  class="request">
                    <small>Already have an account? Click <a href = {{ url_for('users.login')}}>here</a></small>
                </div>
            </form>
        </div>        
    </div>
{% endblock %}

tales/templates/request_token.html
{% extends 'layout.html' %}
{% block content %}
    <div class="request-token">
        <div class="title">
            <h1> Request for password reset</h1>
        </div>
        <div class="form-div">
            <form  method='POST', action="">
                {{ form.hidden_tag() }}
                <fieldset>
                    <legend>Reset Password</legend>
                        <div class="input-div">
                            {{ form.email.label(class_="form-label") }}
                            <div>
                                {% if form.email.errors %}
                                    {{ form.email(class_="form-input") }}
                                    <div  class="error-div">
                                        {% for error in form.email.errors %}
                                            <span>{{ error}}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{form.email(class_='form-input') }}
                                {% endif %}
                            </div>
                        </div>
                </fieldset> 
                <div class="submit-div">
                    {{ form.submit(class_="submit-btn") }}
                </div>            
            </form>
        </div>
    </div>
{% endblock %}

tales/templates/reset_token.html
{% extends 'layout.html' %}
{% block content %}
    <div class="reset-token">
        <div class="title">
            <h1> Reset Your Password</h1>
        </div>
        <div class="form-div">
            <form  method='POST', action="">
                {{ form.hidden_tag() }}
                <fieldset>
                    <legend>Reset Password</legend>
                        <div class="input-div">
                            {{ form.password.label (class_="form-label") }}
                                {% if form.password.errors %}
                                    {{ form.password(class_="form-input") }}
                                    <div class="error-div">
                                        {% for error in form.password.errors %}
                                            <span>{{ error}}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{form.password(class_='form-input') }}
                                {% endif %}
                            </div>
                        </div>
                        <div class="input-div">
                            {{ form.confirm_password.label(class_="form-label") }}
                                {% if form.confirm_password.errors %}
                                    {{ form.confirm_password(class_="form-input") }}
                                    <div class="error-div">
                                        {% for error in form.confirm_password.errors %}
                                            <span>{{ error}}</span>
                                        {% endfor %}
                                    </div>
                                {% else %}
                                    {{form.confirm_password(class_="form-input") }}
                                {% endif %}
                            </div>
                        </div>
                </fieldset> 
                <div class="submit-div">
                    {{ form.submit(class_="submit-btn") }}
                </div>            
            </form>
        </div>
    </div>
{% endblock %}

tales/templates/user.html
{% extends 'layout.html' %}
{% block content%}
    <div class="home-page">
        <div class="title">
            <h1>{{ user.username }} (No of Blogs:{{post.total}})</h1>
        </div>
        <div class="post-container">
            {% for post in post.items %}
                <div class="article">
                    <div class="post-image">
                        <img src={{ url_for('static', filename='profilepic/{}'.format(post.author.image))}}>
                    </div>
                    <div class="post-author">
                        <a href={{url_for('users.user_page', username=post.author.username)}}>{{ post.author.username}}</a>
                        <small>{{ post.date_posted.strftime('%Y-%m-%d')}}</small>
                    </div>
                    <div class="post-content">
                        <a href={{url_for('posts.edit_post', post_id=post.id)}}><h3>{{ post.title }}</h3></a>
                        <p>{{ post.content }}</p>
                    </div>
                </div>
            {% endfor %}
            <div class="pages">
                {% for page_num in post.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2)%}
                {% if page_num %}
                    {% if post.page == page_num %}
                        <a class="current-page" href={{ url_for('users.user_page', username=user.username, page=page_num)}}>{{ page_num }}</a>
                    {% else %}
                        <a class="other-pages" href={{ url_for('users.user_page', username=user.username, page=page_num)}}>{{ page_num }}</a>
                    {% endif %}
                {% endif %}
            {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}